package org.lf.utils.servlet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.bindings.xformat.ObjectFactory;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-21T08:41:47.955+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://szft.lf.org", name = "MyServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface SzftWebService {

    @WebResult(name = "return", targetNamespace = "http://szft.lf.org")
    @Action(input = "urn:getPlAj", output = "urn:getPlAjResponse")
    @RequestWrapper(localName = "getPlAj", targetNamespace = "http://szft.lf.org", className = "org.lf.GetPlAj")
    @WebMethod(action = "urn:getPlAj")
    @ResponseWrapper(localName = "getPlAjResponse", targetNamespace = "http://szft.lf.org", className = "org.lf.GetPlAjResponse")
    public java.lang.String getPlAj(
        @WebParam(name = "userid", targetNamespace = "http://szft.lf.org")
        java.lang.String userid,
        @WebParam(name = "pwd", targetNamespace = "http://szft.lf.org")
        java.lang.String pwd,
        @WebParam(name = "requestXML", targetNamespace = "http://szft.lf.org")
        java.lang.String requestXML
    );
}
